apiVersion: v1
kind: Namespace
metadata:
  name: devpods
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-alvo
  namespace: devpods
  labels:
    app.kubernetes.io/app: nginx-app-alvo
spec:
  containers:
    - name: pod-nginx
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
          hostPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-alvo
  namespace: devpods
spec:
  selector:
    app.kubernetes.io/name: nginx-app-alvo
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30082