apiVersion: v1
kind: Namespace
metadata:
  name: escala

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-escalar
  namespace: escala
  labels:
    app-deploy: nginx-deploy-escalar
spec:
  replicas: 1
  selector:
    matchLabels:
      app-deploy: nginx-deploy-escalar
  template:
    metadata:
      labels:
        app-deploy: nginx-deploy-escalar
    spec:
      containers:
        - name: nginx-deploy-escalar
          image: nginx:latest
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-autoscaler
  namespace: escala
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deploy-escalar
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---
apiVersion: v1
kind: Service
metadata:
  name: svc-loadbalancer
  namespace: escala
spec:
  type: LoadBalancer
  selector:
    app-deploy: nginx-deploy-escalar
  ports:
    - name: http
      port: 6000
      targetPort: 80
  externalIPs:
    - 
