apiVersion: v1
kind: Namespace
metadata:
    name: isolamento
---
apiVersion: v1
kind: Pod
metadata:
    name: pod-observar
    namespace: isolamento
    labels:
        app.kubernetes.io/app: pod-observar
spec:
    containers:
        - name: pod-observar
          image: nginx:latest
          ports:
              - name: http
                containerPort: 80
                hostPort: 4500
---
apiVersion: v1
kind: Service
metadata:
    name: svc-observar
    namespace: isolamento
spec:
    selector:
        app.kubernetes.io/name: pod-observar
    type: NodePort
    ports:
        - protocol: TCP
          port: 80
          nodePort: 30082
