apiVersion: v1
kind: Namespace
metadata:
    name: isolamento
---
apiVersion: v1
kind: Pod
metadata:
    name: pod-p-atacar
    namespace: isolamento
    labels:
        app.kubernetes.io/app: pod-p-atacar
spec:
    containers:
        - name: pod-p-atacar
          image: nginx:latest
          ports:
              - name: http
                containerPort: 80
                hostPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: svc-p-atacar
    namespace: isolamento
spec:
    selector:
        app.kubernetes.io/name: pod-p-atacar
    type: NodePort
    ports:
        - protocol: TCP
          port: 80
          nodePort: 30080
