apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
    type: LoadBalancer
    selector:
        app:  grafana-deployment
    ports:
        - port: 3000
          targetPort: 3000
    externalIPs:
        -  # External IPs