apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app: grafana
  port:
    - protocol: TCP
      port: 80
      targetPort: 3000
   externalIPs:
        -  # your external IP
 