apiVersion: v1
kind: Pod
metadata:
    name: pod-p-atacar
    namespace: isolamento
    labels:
        app.kubernetes.io/app: pod-p-atacar
spec:
    containers:
        - name: pod-p-atacar
          image: nginx:latest
          ports:
              - name: http
                containerPort: 80
                hostPort: 5000
