apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-escalar
  namespace: with-hpa 
  labels:
    app-deploy: nginx-deploy-escalar
spec:
  replicas: 1
  selector:
    matchLabels:
      app-deploy: nginx-deploy-escalar
  template:
    metadata:
      labels:
        app-deploy: nginx-deploy-escalar
    spec:
      containers:
        - name: nginx-deploy-escalar
          image: nginx:latest
          resources:
            limits:
              cpu: "1000m" # 1 CPU
              memory: "1Gi"
            requests:
              cpu: "200m" # 0.2 CPU
              memory: "512Mi"
          ports:
            - containerPort: 80
  minReadySeconds: 5